import math
print(math.sqrt(4))
print(math.ceil(1.333))
print(math.floor(1.333))
print(math.factorial(5))
print(math.fabs(-4))
print(math.pow(4,2))
print(math.log2(2))
print(math.log10(2))
print(math.pi)
print(math.e)